version: '3.8'

services:
  web:
    build: .
    command: gunicorn seo_work_log.wsgi:application --bind 0.0.0.0:8090 --workers 4 --threads 4
    volumes:
      - .:/app
      - /home/seodashboard/htdocs/seodashboard.technotch.dev/pythonseodash2/static:/app/static
      - /home/seodashboard/htdocs/seodashboard.technotch.dev/pythonseodash2/media:/app/media
    ports:
      - "127.0.0.1:8090:8090"
    environment:
      - DJANGO_SETTINGS_MODULE=seo_work_log.settings
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}

volumes:
  static_volume:
  media_volume: 