services:
  web:
    build: .
    command: gunicorn seo_work_log.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=seo_work_log.settings
      - MYSQL_DATABASE=seo_work_log
      - MYSQL_USER=seo_user
      - MYSQL_PASSWORD=seo_password
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=seo_work_log
      - MYSQL_USER=seo_user
      - MYSQL_PASSWORD=seo_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3307:3306"

volumes:
  mysql_data:
  static_volume:
  media_volume: 