# Generated by Django 5.1.4 on 2024-12-26 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_project', models.BooleanField(default=True)),
                ('notify_new_log', models.BooleanField(default=True)),
                ('notify_report', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'System Default')], default='light', max_length=10)),
                ('date_format', models.CharField(choices=[('MM/DD/YYYY', 'MM/DD/YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='YYYY-MM-DD', max_length=20)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], default='pdf', max_length=10)),
                ('report_logo', models.ImageField(blank=True, null=True, upload_to='report_logos/')),
                ('ga_tracking_id', models.CharField(blank=True, max_length=50)),
                ('gsc_verification', models.CharField(blank=True, max_length=100)),
                ('smtp_host', models.CharField(blank=True, max_length=100)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_security', models.CharField(choices=[('tls', 'TLS'), ('ssl', 'SSL'), ('none', 'None')], default='tls', max_length=10)),
                ('auto_backup', models.BooleanField(default=False)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
