# Generated by Django 5.1.4 on 2024-12-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240214_1234'),
        ('core', '0002_usersettings'),
    ]

    operations = [
    ]
