# Generated by Django 5.1.4 on 2024-12-26 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_0002_auto_20240214_1234_0002_usersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seolog',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='seolog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='seolog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='seolog',
            name='off_page_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seolog',
            name='on_page_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seolog',
            name='providers',
            field=models.ManyToManyField(blank=True, related_name='assigned_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seolog',
            name='off_page_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seolog',
            name='on_page_work',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_assigned', 'Project Assigned'), ('seo_log_added', 'SEO Log Added'), ('report_generated', 'Report Generated'), ('project_completed', 'Project Completed'), ('comment_added', 'Comment Added'), ('file_uploaded', 'File Uploaded')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='seo_logs/%Y/%m/%d/')),
                ('work_type', models.CharField(choices=[('on_page', 'On-Page'), ('off_page', 'Off-Page')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('seo_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.seolog')),
            ],
            options={
                'verbose_name': 'SEO Log File',
                'verbose_name_plural': 'SEO Log Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
