# Generated by Django 5.1.4 on 2024-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='report_sections', to='core.seologfile'),
        ),
        migrations.AddField(
            model_name='reportsection',
            name='seo_logs',
            field=models.ManyToManyField(blank=True, related_name='report_sections', to='core.seolog'),
        ),
        migrations.AlterField(
            model_name='reportsection',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
