# Generated by Django 5.1.4 on 2024-12-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_is_active_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('provider', 'Provider'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
