# Generated by Django 5.1.4 on 2024-12-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_report_options_remove_report_is_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sections',
            field=models.ManyToManyField(through='core.ReportSectionOrder', to='core.reportsection'),
        ),
    ]
