# Generated by Django 5.1.4 on 2025-01-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fix_user_model'),
        ('core', '0014_usersettings_keep_as_draft'),
    ]

    operations = [
    ]
