# Generated by Django 5.1.4 on 2025-01-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Project website URL', max_length=255),
        ),
    ]
